# Generated by Django 4.2.7 on 2023-11-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_energydata_added_alter_energydata_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='start_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
