# Generated by Django 4.2.7 on 2023-11-22 16:50

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_energydata_added_alter_energydata_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='added',
            field=app.models.CustomDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='end_year',
            field=app.models.CustomDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='published',
            field=app.models.CustomDateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='start_year',
            field=app.models.CustomDateTimeField(blank=True, null=True),
        ),
    ]
