# Generated by Django 4.2.7 on 2023-11-23 04:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_energydata_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='end_year',
            field=models.CharField(blank=True, default='0000-00-00T00:00', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='start_year',
            field=app.models.CustomDateTimeField(blank=True, default='0000-00-00T00:00', max_length=15, null=True),
        ),
    ]
