# Generated by Django 4.2.7 on 2023-11-25 12:04

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_energydata_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='added',
            field=app.models.CustomDateTimeField(blank=True, default='0000-00-00T00:00', null=True),
        ),
        migrations.AlterField(
            model_name='energydata',
            name='published',
            field=app.models.CustomDateTimeField(blank=True, default='0000-00-00T00:00', null=True),
        ),
    ]
